# Generated by Django 5.2.14 on 2026-05-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.FloatField()),
                ('f2', models.FloatField()),
                ('f3', models.FloatField()),
                ('f4', models.FloatField()),
                ('f5', models.FloatField()),
                ('f6', models.FloatField()),
                ('f7', models.FloatField()),
                ('f8', models.FloatField()),
                ('f9', models.FloatField()),
                ('f10', models.FloatField()),
                ('pca_x', models.FloatField(blank=True, null=True)),
                ('pca_y', models.FloatField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
